# Generated by Django 5.1.2 on 2024-10-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_comentario', to='Gestor_Tareas.usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tarea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_comentario', to='Gestor_Tareas.tarea'),
        ),
    ]
