# Generated by Django 5.1.2 on 2024-10-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Tareas', '0002_alter_comentario_autor_alter_comentario_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='etiquetas_asociadas',
            field=models.ManyToManyField(related_name='tarea_etiqueta', to='Gestor_Tareas.tarea'),
        ),
    ]
