# Generated by Django 5.1.3 on 2024-11-18 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestor_Tareas', '0004_alter_asignacion_tarea_tarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='descipcion',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_creador', to='Gestor_Tareas.usuario'),
        ),
    ]
